
services:
  db-service:
    build:
       context: .
       dockerfile: Dockerfile.psql
       args:
          DB_USER: ${DB_USER}
          DB_NAME: ${DB_NAME}
          DB_HOST: ${DB_HOST}
          DB_PORT: ${DB_PORT}
          DB_VOLUME: ${DB_VOLUME}
          USER_GROUP: ${USER_GROUP}
    container_name: db-service
    restart: unless-stopped
    shm_size: 128mb
    ports:
     - "${DB_PORT}:5432"
    volumes:
      - "${DB_VOLUME}/data:/var/lib/postgresql/data:rw"
      - "${DB_VOLUME}/conf:/etc/postgresql/conf.d:ro"
      - "${DB_VOLUME}/scripts:/docker-entrypoint-initdb.d:ro"
      - "${DB_VOLUME}/assets:/assets:ro"
    environment:
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres-passwd
      - DB_PASSWORD=/run/secrets/db_password
      - DB_USER=${DB_USER}
      - DB_NAME=${DB_NAME}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - SERVICE_TAGS=v1.0.0
      - SERVICE_NAME=db-service
    secrets:
      - postgres-passwd
      - db_password
    networks:
      draft_network:
        aliases:
          - db-service
  adminer:
    image: adminer
    container_name: adminer
    restart: unless-stopped
    ports:
      - "${ADMINER_PORT}:8080"
    environment:
      - ADMINER_DEFAULT_SERVER=db-service
    networks:
      draft_network:
        aliases:
          - adminer
  nest-service:
    build:
      context: .
      dockerfile: Dockerfile.node
      args:
        NODE_PORT: ${NODE_PORT}
        DB_USER: ${DB_USER}
        DB_NAME: ${DB_NAME}
        DB_HOST: ${DB_HOST}
    container_name: nest-service
    restart: unless-stopped
    ports:
      - "${NODE_PORT}:3000"
    volumes:
      - "${NODE_VOLUME}:/home/nodeuser/app:rw"
    environment:
      DB_USER: /run/secrets/db_user
      DB_PASSWORD: /run/secrets/db_password
      DB_NAME: "${DB_NAME}"
      DB_HOST: "${DB_HOST}"
      NODE_PORT: "${NODE_PORT}"
      SERVICE_TAGS: "v1.0.0"
      SERVICE_NAME: nest-service
    secrets:
      - db_password
    depends_on:
      - db-service
    networks:
      draft_network:
        aliases:
          - nest-service

volumes:
  docker: {}
secrets:
  postgres-passwd:
    file: ./secrets/postgres-passwd
  db_password:
    file: ./secrets/db_password
networks:
  draft_network:
    name: tucomida_network
    driver: bridge
    ipam:
      driver: default